server:
  port: 27080
  servlet:
    context-path: '/atp-work-flow'
spring:
  application:
    name: atp-work-flow
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://127.0.0.1:3306/atp?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true'

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #  将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true
  # 存储所有历史
  history-level: full