server:
  port: 27080
  servlet:
    context-path: '/atp-work-flow'
spring:
  application:
    name: atp-work-flow
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://127.0.0.1:3306/atp-flow?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true'
camunda:
  bpm:
    admin-user:
      id: admin
      password: 123456
      first-name: yu
    filter:
      create: all tasks
    webapp:
      application-path: '/camunda'
