spring:
  application:
    name: atp-system
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/atp?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true'
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
